version: '3.8'
services:
    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres
        volumes:
            - /root/db_data:/var/lib/postgresql/data
        build: ./managment
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=tumemes
            - POSTGRES_PASSWORD=${DB_PWD}
            - POSTGRES_DB=tumemes

    tumemes-service:
        container_name: tumemes-service
        ports:
            - "8080:8080"
        environment:
            - DATABASE_CONNECTION=postgres:5432/tumemes
            - DATABASE_USER=tumemes
            - DATABASE_PWD=${DB_PWD}
            - MEME_FOLDER=/memeImages/
            - JWT_SECRET=${JWT_SECRET}
            - SMTP_USERNAME=${SMTP_USERNAME}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        volumes:
            - /var/www/memeImages:/memeImages
        depends_on: 
            - postgres
        build: ./service
