version: '3.8'
services:
    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres
        build: ./managment
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=tumemes
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=tumemes

    tumemes-service:
        container_name: tumemes-service
        ports:
            - "8080:8080"
        environment:
            - DATABASE_CONNECTION=postgres:5432/tumemes
            - DATABASE_USER=tumemes
            - DATABASE_PWD=test
            - MEME_FOLDER=/memes
        volumes:
            - /var/www/memes:/memes
        depends_on: 
            - postgres
        build: ./service
